# **NumPy**

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
print(a)

[1 2 3]


In [ ]:
b = np.array([[1, 2], [3, 4]])
print(b)

[[1 2]
 [3 4]]


In [ ]:
type(a)

numpy.ndarray

In [ ]:
c= [1,2,3]

In [ ]:
type(c)

list

In [ ]:
print(np.zeros((2, 3)))      # 2x3 크기의 0 배열


[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print(np.ones(5))            # 길이 5의 1 배열


[1. 1. 1. 1. 1.]


In [ ]:
print(np.arange(0, 10, 2))   # 0부터 10까지 2씩 증가


[0 2 4 6 8]


In [ ]:
print(np.linspace(0, 1, 5))  # 0~1 사이를 5개로 나눈 배열


[0.   0.25 0.5  0.75 1.  ]


In [ ]:
print(np.random.rand(3))     # 0~1 사이의 난수 3개

[0.6320123  0.76168084 0.08962447]


# **실습문제**

In [ ]:
#문제 1: 다음 조건에 맞는 배열을 생성하고 출력하세요.
#1차원 배열, 5개의 요소, 0으로 초기화된 배열

import numpy as np

a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
# 문제 2: 1부터 10까지의 숫자 중 짝수만 포함하는 배열을 생성하세요.

b = np.arange(2,11,2)
print(b)

[ 2  4  6  8 10]


In [ ]:
# 문제 3: [2, 4, 6] 배열과 [10, 20, 30] 배열을 각각 생성하고, 곱셈 연산을 수행한 결과를 출력하세요.

c = np.array([2,4,6])
d = np.array([10,20,30])
e = c*d
print(e)

[ 20  80 180]


In [ ]:
# 문제 4: 위 배열에서 20보다 큰 요소만 필터링해서 출력하세요.

print(e[e>20])

[ 80 180]


# **Pandas**

In [ ]:
import pandas as pd

In [ ]:
s = pd.Series([10, 20, 30, 40])
print(s)

0    10
1    20
2    30
3    40
dtype: int64


In [ ]:
type(s)

pandas.core.series.Series

In [ ]:
data = {
    '이름': ['홍길동', '김철수', '이영희'],
    '나이': [25, 30, 27],
    '성별': ['남', '남', '여']
}

df = pd.DataFrame(data)
print(df)

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [ ]:
df.to_csv('output_data.csv', index=False)

In [ ]:
df = pd.read_csv('output_data.csv')
print(df.head())  # 처음 5행만 출력

    이름  나이 성별
0  홍길동  25  남
1  김철수  30  남
2  이영희  27  여


In [ ]:
df = pd.read_csv('train_and_test2.csv')
print(df.head())

   Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
0            1  22.0   7.2500    0      1     0       0       0       0   
1            2  38.0  71.2833    1      1     0       0       0       0   
2            3  26.0   7.9250    1      0     0       0       0       0   
3            4  35.0  53.1000    1      1     0       0       0       0   
4            5  35.0   8.0500    0      0     0       0       0       0   

   zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  Embarked  \
0       0  ...        0        0        0       3        0        0       2.0   
1       0  ...        0        0        0       1        0        0       0.0   
2       0  ...        0        0        0       3        0        0       2.0   
3       0  ...        0        0        0       1        0        0       2.0   
4       0  ...        0        0        0       3        0        0       2.0   

   zero.17  zero.18  2urvived  
0        0        0         0 

In [ ]:
print(df.tail())

      Passengerid   Age      Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
1304         1305  28.0    8.0500    0      0     0       0       0       0   
1305         1306  39.0  108.9000    1      0     0       0       0       0   
1306         1307  38.5    7.2500    0      0     0       0       0       0   
1307         1308  28.0    8.0500    0      0     0       0       0       0   
1308         1309  28.0   22.3583    0      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  zero.16  \
1304       0  ...        0        0        0       3        0        0   
1305       0  ...        0        0        0       1        0        0   
1306       0  ...        0        0        0       3        0        0   
1307       0  ...        0        0        0       3        0        0   
1308       0  ...        0        0        0       3        0        0   

      Embarked  zero.17  zero.18  2urvived  
1304       2.0        0        0   

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1309 non-null   int64  
 1   Age          1309 non-null   float64
 2   Fare         1309 non-null   float64
 3   Sex          1309 non-null   int64  
 4   sibsp        1309 non-null   int64  
 5   zero         1309 non-null   int64  
 6   zero.1       1309 non-null   int64  
 7   zero.2       1309 non-null   int64  
 8   zero.3       1309 non-null   int64  
 9   zero.4       1309 non-null   int64  
 10  zero.5       1309 non-null   int64  
 11  zero.6       1309 non-null   int64  
 12  Parch        1309 non-null   int64  
 13  zero.7       1309 non-null   int64  
 14  zero.8       1309 non-null   int64  
 15  zero.9       1309 non-null   int64  
 16  zero.10      1309 non-null   int64  
 17  zero.11      1309 non-null   int64  
 18  zero.12      1309 non-null   int64  
 19  zero.1

In [ ]:
print(df.describe())

       Passengerid          Age         Fare          Sex        sibsp  \
count  1309.000000  1309.000000  1309.000000  1309.000000  1309.000000   
mean    655.000000    29.503186    33.281086     0.355997     0.498854   
std     378.020061    12.905241    51.741500     0.478997     1.041658   
min       1.000000     0.170000     0.000000     0.000000     0.000000   
25%     328.000000    22.000000     7.895800     0.000000     0.000000   
50%     655.000000    28.000000    14.454200     0.000000     0.000000   
75%     982.000000    35.000000    31.275000     1.000000     1.000000   
max    1309.000000    80.000000   512.329200     1.000000     8.000000   

         zero  zero.1  zero.2  zero.3  zero.4  ...  zero.12  zero.13  zero.14  \
count  1309.0  1309.0  1309.0  1309.0  1309.0  ...   1309.0   1309.0   1309.0   
mean      0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
std       0.0     0.0     0.0     0.0     0.0  ...      0.0      0.0      0.0   
min      

In [ ]:
print(df['Age'])

0       22.0
1       38.0
2       26.0
3       35.0
4       35.0
        ... 
1304    28.0
1305    39.0
1306    38.5
1307    28.0
1308    28.0
Name: Age, Length: 1309, dtype: float64


In [ ]:
print(df.loc[0])

Passengerid     1.00
Age            22.00
Fare            7.25
Sex             0.00
sibsp           1.00
zero            0.00
zero.1          0.00
zero.2          0.00
zero.3          0.00
zero.4          0.00
zero.5          0.00
zero.6          0.00
Parch           0.00
zero.7          0.00
zero.8          0.00
zero.9          0.00
zero.10         0.00
zero.11         0.00
zero.12         0.00
zero.13         0.00
zero.14         0.00
Pclass          3.00
zero.15         0.00
zero.16         0.00
Embarked        2.00
zero.17         0.00
zero.18         0.00
2urvived        0.00
Name: 0, dtype: float64


In [ ]:
x = df[df['Age'] < 20]
print(x)

      Passengerid   Age     Fare  Sex  sibsp  zero  zero.1  zero.2  zero.3  \
7               8   2.0  21.0750    0      3     0       0       0       0   
9              10  14.0  30.0708    1      1     0       0       0       0   
10             11   4.0  16.7000    1      1     0       0       0       0   
14             15  14.0   7.8542    1      0     0       0       0       0   
16             17   2.0  29.1250    0      4     0       0       0       0   
...           ...   ...      ...  ...    ...   ...     ...     ...     ...   
1280         1281   6.0  21.0750    0      3     0       0       0       0   
1283         1284  13.0  20.2500    0      0     0       0       0       0   
1286         1287  18.0  60.0000    1      1     0       0       0       0   
1294         1295  17.0  47.1000    0      0     0       0       0       0   
1300         1301   3.0  13.7750    1      1     0       0       0       0   

      zero.4  ...  zero.12  zero.13  zero.14  Pclass  zero.15  

In [ ]:
y = df.dropna(inplace=True)
print(df.info())

<class 'pandas.core.frame.DataFrame'>
Index: 1307 entries, 0 to 1308
Data columns (total 28 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Passengerid  1307 non-null   int64  
 1   Age          1307 non-null   float64
 2   Fare         1307 non-null   float64
 3   Sex          1307 non-null   int64  
 4   sibsp        1307 non-null   int64  
 5   zero         1307 non-null   int64  
 6   zero.1       1307 non-null   int64  
 7   zero.2       1307 non-null   int64  
 8   zero.3       1307 non-null   int64  
 9   zero.4       1307 non-null   int64  
 10  zero.5       1307 non-null   int64  
 11  zero.6       1307 non-null   int64  
 12  Parch        1307 non-null   int64  
 13  zero.7       1307 non-null   int64  
 14  zero.8       1307 non-null   int64  
 15  zero.9       1307 non-null   int64  
 16  zero.10      1307 non-null   int64  
 17  zero.11      1307 non-null   int64  
 18  zero.12      1307 non-null   int64  
 19  zero.13    

In [ ]:
x1 = df.groupby('Sex')['Age'].mean()
print(x1)

Sex
0    30.017888
1    28.479720
Name: Age, dtype: float64
